# Generated by Django 5.2.6 on 2025-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereço',
            new_name='Endereco',
        ),
    ]
